name: mri_toolkit
dependencies:
- python=3.9
- pip
- pip:
    - pandas    
    - scipy
    - numpy
    - scikit-image
    - scikit-learn
    - opencv-python
    - matplotlib
    - nilearn
    - itk-elastix
    - SimpleITK
    - nibabel
    - intensity-normalization[ants]
    - jupyter
